# Application Git repository and version to be installed
# - Production: repository: maestrano, branch: mno-master
# - UAT:        repository: maestrano, branch: mno-develop
# - Local:      repository: my_repository, branch: my_branch
application_version: mno-master
application_repository: maestrano
